### ISSUE TITLE
Can't see details of the roll

### ISSUE THREAD

**Issue by AMaciaga** [Xbozon/rpg-styled-ui#94]
Hi. When I try to view details of the roll, nothing happens when I click on the expand arrow
![image](https://github.com/Xbozon/rpg-styled-ui/assets/43912213/46fdb303-3ea3-436a-8b50-27f0cd56cead)
![image](https://github.com/Xbozon/rpg-styled-ui/assets/43912213/0fb39be5-4a92-42b4-a7d2-ae0e67e19b17)
The issue only occurs when ui style module is enabled.

**Comment by Sasmira** [comment]
Hello Hello, 
which system version?
which interface version?
your module is up to date ?
have you tried with the interface only?

**Comment by Blacke-Sotce** [comment]
I am having the same problem seeing the rolls made. The final result appears (after applying the bonuses) but after clicking on the chat, the dice roll (the formula) is not shown. I attach three images so that I can be understood.

In this first one there are no active modules:
![imagen](https://github.com/Xbozon/rpg-styled-ui/assets/112676897/96681442-f72e-459d-ba63-2bcb9c2be97b)

In this Only the UI is active:
![imagen](https://github.com/Xbozon/rpg-styled-ui/assets/112676897/fcf8dc4a-c6e1-4493-b09b-b45c9bcb2807)

In this (from another game) there are active modules, but not the UI:
![imagen](https://github.com/Xbozon/rpg-styled-ui/assets/112676897/54807ba8-b057-45ef-9efc-ab96a9509b82)

I have tested with and without the active module, and with the module alone. And yes, indeed the conflict seems to be related to this.

**My usage data**

> Software version: v11s - Build 315
> Game System version: 3.0.3
> Module version: v1.1.8

**Comment by Sasmira** [comment]
PR added

<img src="https://puu.sh/K1HES/565c8681cc.png">

**Comment by Xbozon** [comment]
@AMaciaga @Sasmira Merged, thank you!
